/*
 * Copyright (C) 2024. Huawei Device Co., Ltd. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Apache-2.0 license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Apache-2.0 license for more details.
 */

/**
 * Common constants for all features.
 */
export class Constants {
  /**
   * The content type.
   */
  static readonly CONTENT_TYPE: string = 'Content-Type';
  /**
   * The content type is application/json.
   */
  static readonly APPLICATION_JSON: string = 'application/json';
  /**
   * The radix is ten.
   */
  static readonly RADIX_TEN: number = 10;
  /*
 * Hot Update Resource Storage Path
 */
  static readonly UPDATE_STORAGE_PATH: string = 'update';
  /**
   * The download config title is applet updating.
   */
  static readonly APPLET_UPDATING: string = 'Applet updating...';
  /**
   * The header Key of Connection.
   */
  static readonly HEADER_KEY_CONNECTION: string = 'Connection';
  /**
   * The header value of keep-alive.
   */
  static readonly HEADER_VALUE_KEEP_ALIVE: string = 'keep-alive';
  /**
   * The header Key of Cache-Control.
   */
  static readonly HEADER_KEY_CACHE_CONTROL: string = 'Cache-Control';
  /**
   * The header value of no-cache.
   */
  static readonly HEADER_VALUE_NO_CACHE: string = 'no-cache';
  /**
   * The suffix is .js.
   */
  static readonly SUFFIX_JS: string = '.js';
  /**
   * The suffix is .css.
   */
  static readonly SUFFIX_CSS: string = '.css';
  /**
   * The suffix is .html.
   */
  static readonly SUFFIX_HTML: string = '.html';
  /**
   * The suffix is .hml.
   */
  static readonly SUFFIX_HML: string = '.hml';
  /**
   * The suffix is .jpg.
   */
  static readonly SUFFIX_JPG: string = '.jpg';
  /**
   * The suffix is .jpeg.
   */
  static readonly SUFFIX_JPEG: string = '.jpeg';
  /**
   * The suffix is .png.
   */
  static readonly SUFFIX_PNG: string = '.png';
  /**
   * The suffix is .txt.
   */
  static readonly SUFFIX_TXT: string = '.txt';
  /**
   * The mime type is application/javascript.
   */
  static readonly MIME_TYPE_APPLICATION_JAVASCRIPT: string = 'application/javascript';
  /**
   * The mime type is text/css.
   */
  static readonly MIME_TYPE_TEXT_CSS: string = 'text/css';
  /**
   * The mime type is text/html.
   */
  static readonly MIME_TYPE_TEXT_HTML: string = 'text/html';
  /**
   * The mime type is image/jpeg.
   */
  static readonly MIME_TYPE_IMAGE_JPEG: string = 'image/jpeg';
  /**
   * The mime type is image/png.
   */
  static readonly MIME_TYPE_IMAGE_PNG: string = 'image/png';
  /**
   * The mime type is text/plain.
   */
  static readonly MIME_TYPE_TEXT_PLAIN: string = 'text/plain';
  /**
   * The mime type is application/octet-stream.
   */
  static readonly MIME_TYPE_APPLICATION_OCTET_STREAM: string = 'application/octet-stream';
  /**
   * The Encoding of utf-8.
   */
  static readonly ENCODING_UTF_8: string = 'utf-8';
  /**
   * The response code is 200.
   */
  static readonly RESPONSE_CODE: number = 200;
  /**
   * The reason message ok.
   */
  static readonly REASON_MESSAGE_OK: string = 'OK';
}