/*
 * Copyright (C) 2024. Huawei Device Co., Ltd. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Apache-2.0 license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Apache-2.0 license for more details.
 */

export enum RouteType {
  MULTI_MULTI,
  MULTI_SINGLE,
  SINGLE_SINGLE
}

export enum PushPageType {
  WEB_TO_WEB,
  NATIVE_TO_NATIVE,
  HYBRID_TO_HYBRID
}